export const Skills = [
  "HTML",
  "CSS",
  "JavaScript",
  "Typescript",
  "React.js",
  "Next.js",
  "SASS",
  "Material UI",
  "ShadCnUI",
  "Figma",
  "Sonar Cloud",
  "Jira",
  "Git",
  "Bitbucket",
  "Vite",
  "Core Web Vitals",
  "REST API",
  "Code Splitting",
  "Lazy Loading",
  "React Router",
  "Context API",
  "React Hooks",
  "Redux Toolkit",
  "Tree Shaking",
  "Webpack",
  "ES6",
  "Data Structure & Algorithms",
  "Problem Solving",
  "Object Oriented Programming",
  "C++",
  "Java",

  "Bootstrap",
  "Node.js",
  "Express.js",
  "MongoDB",
  "Firebase",
];
